###
GET http://localhost:8000/api/residents

###
GET http://localhost:8000/api/rides

###
POST http://localhost:8000/api/rides
Content-Type: application/json; charset=UTF-8
Accept: application/json
Cache-Control: no-cache

{
  "decision": {
    "id":  85
  },
  "taxi": {
    "id":  71
  },
  "location": {
    "id":  205
  },
  "destination": {
    "houseNumber":  305,
    "postalCode": "3031XR"
  },
  "distance": 3.7
}

###
GET http://localhost:8000/api/rides?taxi=71