###
GET http://localhost:8000/api/residents

###
POST http://localhost:8000/api/rides
Content-Type: application/json; charset=UTF-8
Accept: application/json
Cache-Control: no-cache

{
  "decision": {
    "id":  309
  },
  "taxi": {
    "id":  231
  },
  "location": {
    "id":  655
  },
  "destination": {
    "houseNumber":  305,
    "postalCode": "3031XR"
  },
  "distance": 100.1
}

###
GET http://localhost:8000/api/rides

###
GET http://localhost:8000/api/rides?taxi=71